    require('dotenv').config();
const mongoose = require('mongoose');

// Import des modèles
const User = require('../src/models/User');
const Category = require('../src/models/Category');
const Product = require('../src/models/Product');
const AdminSettings = require('../src/models/AdminSettings');

const connectDB = require('../src/config/database');

const seedData = async () => {
  try {
    await connectDB();

    console.log('🧹 Cleaning existing data...');
    // Nettoyer les collections existantes
    await User.deleteMany({});
    await Category.deleteMany({});
    await Product.deleteMany({});
    await AdminSettings.deleteMany({});

    console.log('👤 Creating admin user...');
    // Créer un utilisateur admin avec mot de passe hashé
    const adminUser = new User({
      name: 'Admin Furniture Store',
      email: 'admin@furniture-store.com',
      password: '$2a$12$Ui0GJf504HHmEiiw05l1d.zWPf5CTLMrS0rXbNsmMG7a9dksM.XO6',
      role: 'admin'
    });
    // Le hook pre-save essaiera de hasher à nouveau, donc on bypasse avec updateOne
    await adminUser.save();
    // Restaurer le hash directement pour éviter un double hachage
    await User.updateOne(
      { _id: adminUser._id },
      { password: '$2a$12$Ui0GJf504HHmEiiw05l1d.zWPf5CTLMrS0rXbNsmMG7a9dksM.XO6' }
    );

    console.log('🏷️ Creating categories...');
    // Créer des catégories
    const categories = await Category.insertMany([
      { 
        name: 'Chambres', 
        slug: 'chambres', 
        description: 'Lits, armoires, commodes pour votre chambre',
        sortOrder: 1
      },
      { 
        name: 'Salons', 
        slug: 'salons', 
        description: 'Canapés, fauteuils, tables basses pour votre salon',
        sortOrder: 2
      },
      { 
        name: 'Cuisines', 
        slug: 'cuisines', 
        description: 'Cuisines, tables, chaises pour votre cuisine',
        sortOrder: 3
      },
      { 
        name: 'Bureaux', 
        slug: 'bureaux', 
        description: 'Bureaux, chaises de bureau, rangements',
        sortOrder: 4
      }
    ]);

    // Créer un mapping des catégories
    const categoryMap = {
      'chambres': categories.find(c => c.slug === 'chambres')._id,
      'salons': categories.find(c => c.slug === 'salons')._id,
      'cuisines': categories.find(c => c.slug === 'cuisines')._id,
      'bureaux': categories.find(c => c.slug === 'bureaux')._id
    };

    console.log('🛋️ Creating 45 products...');
    // Créer tous les produits du catalogue
    const products = [
      // Chambres (9)
      { name: 'Chambre Complète Moderne Wengé', description: 'Ensemble complet pour chambre moderne avec finition wengé', price: 450000, originalPrice: 420000, discount: 0, category: categoryMap['chambres'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1675537843200-78c1a0ea1736?q=80&w=687&auto=format&fit=crop', publicId: 'chambre-1-1', alt: 'Chambre wengé' }], dimensions: { length: 200, width: 160, height: 120, weight: 150 }, materials: ['Bois', 'Mélaminé'], colors: ['Wengé', 'Noir'], sku: 'CHAMBRE-WENGE-001', featured: true, inStock: true, stockQuantity: 12, brand: 'MeubleMarket Premium', tags: ['chambre complète', 'moderne', 'wengé'], rating: { average: 4.8, count: 45 } },
      { name: 'Chambre Scandinave Blanc', description: 'Ensemble chambre style scandinave en blanc', price: 380000, originalPrice: 380000, discount: 0, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1171&auto=format&fit=crop', publicId: 'chambre-2', alt: 'Chambre scandinave' }], dimensions: { length: 190, width: 140, height: 110, weight: 120 }, materials: ['Bois', 'MDF'], colors: ['Blanc', 'Bois clair'], sku: 'CHAMBRE-SCANDI-001', featured: false, inStock: true, stockQuantity: 8, brand: 'Nordic Home', tags: ['scandinave', 'blanc', 'minimaliste'], rating: { average: 4.6, count: 32 } },
      { name: 'Lit Double Capitonné', description: 'Lit double avec tête de lit capitonnée', price: 280000, originalPrice: 280000, discount: 0, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=880&auto=format&fit=crop', publicId: 'chambre-3', alt: 'Lit capitonné' }], dimensions: { length: 200, width: 160, height: 130, weight: 80 }, materials: ['Bois', 'Tissu'], colors: ['Gris', 'Beige'], sku: 'LIT-CAPITONNE-001', featured: true, inStock: true, stockQuantity: 15, brand: 'Confort Plus', tags: ['lit', 'capitonné', 'confort'], rating: { average: 4.7, count: 28 } },
      { name: 'Chambre Minimaliste Gris', description: 'Lit double avec armoire 3 portes', price: 395000, originalPrice: 455000, discount: 13, category: categoryMap['chambres'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1683120852623-143817d6400b?q=80&w=1176&auto=format&fit=crop', publicId: 'chambre-4', alt: 'Chambre minimaliste' }], dimensions: { length: 200, width: 160, height: 120, weight: 130 }, materials: ['Bois', 'Mélaminé'], colors: ['Gris', 'Blanc'], sku: 'CHAMBRE-MINI-001', featured: false, inStock: true, stockQuantity: 9, brand: 'City Home', tags: ['chambre', 'minimaliste'], rating: { average: 4.5, count: 19 } },
      { name: 'Chambre Bois Naturel', description: 'Ambiance chaleureuse en bois naturel', price: 510000, originalPrice: 585000, discount: 13, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1157&auto=format&fit=crop', publicId: 'chambre-5', alt: 'Chambre bois' }], dimensions: { length: 200, width: 160, height: 115, weight: 145 }, materials: ['Bois massif'], colors: ['Bois naturel'], sku: 'CHAMBRE-BOIS-001', featured: true, inStock: true, stockQuantity: 6, brand: 'Nature Line', tags: ['bois', 'naturel'], rating: { average: 4.7, count: 22 } },
      { name: 'Chambre Compacte Urbain', description: 'Solution compacte pour petits espaces', price: 335000, originalPrice: 385000, discount: 13, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1170&auto=format&fit=crop', publicId: 'chambre-6', alt: 'Chambre compacte' }], dimensions: { length: 190, width: 140, height: 110, weight: 110 }, materials: ['MDF', 'Métal'], colors: ['Blanc', 'Chêne'], sku: 'CHAMBRE-COMPACT-001', featured: false, inStock: true, stockQuantity: 14, brand: 'UrbanFit', tags: ['compact', 'urbain'], rating: { average: 4.4, count: 16 } },
      { name: 'Chambre Vintage', description: 'Finitions rétro élégantes', price: 470000, originalPrice: 540000, discount: 13, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1170&auto=format&fit=crop', publicId: 'chambre-7', alt: 'Chambre vintage' }], dimensions: { length: 200, width: 160, height: 120, weight: 135 }, materials: ['Bois', 'Tissu'], colors: ['Crème', 'Noir'], sku: 'CHAMBRE-VINTAGE-001', featured: false, inStock: true, stockQuantity: 7, brand: 'RetroHome', tags: ['vintage'], rating: { average: 4.6, count: 20 } },
      { name: 'Chambre Premium Noir & Or', description: 'Design premium avec détails dorés', price: 690000, originalPrice: 790000, discount: 13, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=1074&auto=format&fit=crop', publicId: 'chambre-8', alt: 'Chambre premium' }], dimensions: { length: 210, width: 180, height: 120, weight: 160 }, materials: ['Bois', 'Métal'], colors: ['Noir', 'Or'], sku: 'CHAMBRE-PREMIUM-001', featured: true, inStock: true, stockQuantity: 4, brand: 'GoldLine', tags: ['premium', 'noir-or'], rating: { average: 4.8, count: 11 } },
      { name: 'Chambre Nature & Lumière', description: 'Ambiance lumineuse et zen', price: 520000, originalPrice: 598000, discount: 13, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?q=80&w=1170&auto=format&fit=crop', publicId: 'chambre-9', alt: 'Chambre zen' }], dimensions: { length: 200, width: 160, height: 115, weight: 140 }, materials: ['Bois', 'Rotin'], colors: ['Beige', 'Blanc'], sku: 'CHAMBRE-ZEN-001', featured: false, inStock: true, stockQuantity: 6, brand: 'ZenHome', tags: ['zen', 'nature'], rating: { average: 4.6, count: 17 } },

      // Salons (7)
      { name: 'Salon d\'angle 7 places Cuir', description: 'Grand salon d\'angle en cuir véritable', price: 520000, originalPrice: 480000, discount: 0, category: categoryMap['salons'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1673014200221-524696a1edd9?q=80&w=1231&auto=format&fit=crop', publicId: 'salon-1-1', alt: 'Salon cuir' }], dimensions: { length: 300, width: 250, height: 90, weight: 180 }, materials: ['Cuir véritable', 'Bois'], colors: ['Noir', 'Marron', 'Blanc'], sku: 'SALON-CUIR-001', featured: true, inStock: true, stockQuantity: 5, brand: 'Luxury Living', tags: ['salon', 'cuir', 'angle', '7 places'], rating: { average: 4.9, count: 67 } },
      { name: 'Canapé 3+2+1 Tissu Moderne', description: 'Ensemble canapé 3+2+1 places en tissu', price: 285000, originalPrice: 285000, discount: 0, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1628624998771-ed120a552e74?q=80&w=1170&auto=format&fit=crop', publicId: 'salon-2', alt: 'Canapé tissu' }], dimensions: { length: 200, width: 90, height: 85, weight: 100 }, materials: ['Tissu', 'Bois'], colors: ['Gris', 'Bleu', 'Beige'], sku: 'SALON-TISSU-001', featured: false, inStock: true, stockQuantity: 10, brand: 'Confort Home', tags: ['canapé', 'tissu', 'ensemble'], rating: { average: 4.5, count: 42 } },
      { name: 'Canapé d\'angle Tissu Premium', description: 'Grand canapé d\'angle en tissu premium', price: 365000, originalPrice: 420000, discount: 13, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1628624998771-ed120a552e74?q=80&w=1170&auto=format&fit=crop', publicId: 'salon-3', alt: 'Canapé angle' }], dimensions: { length: 280, width: 200, height: 90, weight: 120 }, materials: ['Tissu', 'Bois'], colors: ['Gris', 'Bleu'], sku: 'SALON-ANGLE-001', featured: false, inStock: true, stockQuantity: 8, brand: 'Confort Plus', tags: ['angle', 'tissu'], rating: { average: 4.5, count: 21 } },
      { name: 'Salon Design Beige', description: 'Ensemble 3+2 places design', price: 315000, originalPrice: 362000, discount: 13, category: categoryMap['salons'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1678790910571-e7260e9bc730?q=80&w=1170&auto=format&fit=crop', publicId: 'salon-4', alt: 'Salon design' }], dimensions: { length: 220, width: 90, height: 85, weight: 95 }, materials: ['Tissu', 'Bois'], colors: ['Beige'], sku: 'SALON-DESIGN-001', featured: false, inStock: true, stockQuantity: 10, brand: 'Design House', tags: ['design'], rating: { average: 4.4, count: 18 } },
      { name: 'Canapé Velours Vert', description: 'Canapé 3 places en velours', price: 275000, originalPrice: 315000, discount: 13, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1685085401515-2555080b9821?q=80&w=1170&auto=format&fit=crop', publicId: 'salon-5', alt: 'Canapé velours' }], dimensions: { length: 200, width: 90, height: 85, weight: 85 }, materials: ['Velours', 'Bois'], colors: ['Vert'], sku: 'SALON-VELOURS-001', featured: true, inStock: true, stockQuantity: 11, brand: 'Velvet Line', tags: ['velours'], rating: { average: 4.6, count: 26 } },
      { name: 'Salon Familial Gris', description: 'Grand salon familial confortable', price: 335000, originalPrice: 382000, discount: 12, category: categoryMap['salons'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1733514691690-4ff581def209?q=80&w=1171&auto=format&fit=crop', publicId: 'salon-6', alt: 'Salon familial' }], dimensions: { length: 240, width: 95, height: 85, weight: 110 }, materials: ['Tissu', 'Bois'], colors: ['Gris'], sku: 'SALON-FAMILIA-001', featured: false, inStock: true, stockQuantity: 7, brand: 'FamilyHome', tags: ['familial'], rating: { average: 4.3, count: 14 } },
      { name: 'Fauteuil Lounge', description: 'Fauteuil lounge confortable', price: 145000, originalPrice: 165000, discount: 12, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1702865071803-cb154cd45f48?q=80&w=1170&auto=format&fit=crop', publicId: 'salon-7', alt: 'Fauteuil lounge' }], dimensions: { length: 90, width: 80, height: 95, weight: 25 }, materials: ['Tissu', 'Métal'], colors: ['Bleu', 'Gris'], sku: 'SALON-FAUTEUIL-001', featured: false, inStock: true, stockQuantity: 18, brand: 'Relaxo', tags: ['fauteuil'], rating: { average: 4.2, count: 9 } },

      // Cuisines (5)
      { name: 'Cuisine Complète L-Shape', description: 'Cuisine moderne en forme de L', price: 890000, originalPrice: 820000, discount: 0, category: categoryMap['cuisines'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1680382578871-32ce66f9ae25?q=80&w=1332&auto=format&fit=crop', publicId: 'cuisine-1-1', alt: 'Cuisine L-shape' }], dimensions: { length: 350, width: 250, height: 240, weight: 300 }, materials: ['Bois', 'Granite', 'Inox'], colors: ['Blanc', 'Gris', 'Noir'], sku: 'CUISINE-L-001', featured: true, inStock: true, stockQuantity: 3, brand: 'Kitchen Pro', tags: ['cuisine complète', 'moderne', 'L-shape'], rating: { average: 4.8, count: 35 } },
      { name: 'Table + 6 Chaises Salle à Manger', description: 'Ensemble table et chaises pour salle à manger', price: 245000, originalPrice: 245000, discount: 0, category: categoryMap['cuisines'], images: [{ url: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?q=80&w=687&auto=format&fit=crop', publicId: 'cuisine-2', alt: 'Table chaises' }], dimensions: { length: 180, width: 90, height: 75, weight: 90 }, materials: ['Bois massif'], colors: ['Chêne', 'Noyer'], sku: 'CUISINE-TABLE-001', featured: false, inStock: true, stockQuantity: 7, brand: 'Wood Craft', tags: ['table', 'chaises', 'salle à manger'], rating: { average: 4.6, count: 29 } },
      { name: 'Cuisine Blanche Épurée', description: 'Cuisine droite blanche très lumineuse', price: 690000, originalPrice: 770000, discount: 10, category: categoryMap['cuisines'], images: [{ url: 'https://images.unsplash.com/photo-1602028644961-dd13cb5d0c72?q=80&w=1170&auto=format&fit=crop', publicId: 'cuisine-3', alt: 'Cuisine blanche' }], dimensions: { length: 320, width: 60, height: 240, weight: 260 }, materials: ['MDF', 'Inox'], colors: ['Blanc'], sku: 'CUISINE-BLANC-001', featured: false, inStock: true, stockQuantity: 4, brand: 'Kitchen Pro', tags: ['cuisine', 'blanc'], rating: { average: 4.6, count: 15 } },
      { name: 'Cuisine Bois & Blanc', description: 'Alliance du bois et du blanc', price: 740000, originalPrice: 820000, discount: 10, category: categoryMap['cuisines'], images: [{ url: 'https://images.unsplash.com/photo-1600122272511-c85c3a0209f9?q=80&w=1170&auto=format&fit=crop', publicId: 'cuisine-4', alt: 'Cuisine bois blanc' }], dimensions: { length: 340, width: 60, height: 240, weight: 275 }, materials: ['Bois', 'MDF'], colors: ['Bois clair', 'Blanc'], sku: 'CUISINE-BOIS-001', featured: true, inStock: true, stockQuantity: 5, brand: 'Nordic Kitchen', tags: ['bois', 'blanc'], rating: { average: 4.7, count: 19 } },
      { name: 'Cuisine Compacte Studio', description: 'Cuisine compacte idéale studio', price: 295000, originalPrice: 335000, discount: 12, category: categoryMap['cuisines'], images: [{ url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1174&auto=format&fit=crop', publicId: 'cuisine-5', alt: 'Cuisine compacte' }], dimensions: { length: 180, width: 60, height: 220, weight: 150 }, materials: ['MDF', 'Inox'], colors: ['Gris', 'Blanc'], sku: 'CUISINE-COMPACT-001', featured: false, inStock: true, stockQuantity: 9, brand: 'City Kitchen', tags: ['compact'], rating: { average: 4.3, count: 12 } },

      // Bureaux (5)
      { name: 'Bureau Direction + Fauteuil', description: 'Ensemble bureau de direction avec fauteuil ergonomique', price: 195000, originalPrice: 195000, discount: 0, category: categoryMap['bureaux'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1681487178876-a1156952ec60?q=80&w=1170&auto=format&fit=crop', publicId: 'bureau-1', alt: 'Bureau direction' }], dimensions: { length: 160, width: 80, height: 75, weight: 70 }, materials: ['Bois', 'Métal', 'Cuir'], colors: ['Noir', 'Marron'], sku: 'BUREAU-DIRECTION-001', featured: false, inStock: true, stockQuantity: 12, brand: 'Office Elite', tags: ['bureau', 'direction', 'fauteuil'], rating: { average: 4.7, count: 38 } },
      { name: 'Bureau Moderne Blanc', description: 'Bureau moderne avec rangements intégrés', price: 145000, originalPrice: 145000, discount: 0, category: categoryMap['bureaux'], images: [{ url: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?q=80&w=1074&auto=format&fit=crop', publicId: 'bureau-2', alt: 'Bureau blanc' }], dimensions: { length: 140, width: 60, height: 75, weight: 40 }, materials: ['MDF', 'Métal'], colors: ['Blanc', 'Gris'], sku: 'BUREAU-BLANC-001', featured: false, inStock: true, stockQuantity: 20, brand: 'Home Office', tags: ['bureau', 'moderne', 'télétravail'], rating: { average: 4.5, count: 24 } },
      { name: 'Bureau Industriel Bois & Métal', description: 'Plateau bois et structure métal', price: 175000, originalPrice: 199000, discount: 12, category: categoryMap['bureaux'], images: [{ url: 'https://images.unsplash.com/photo-1571624436279-b272aff752b5?q=80&w=1172&auto=format&fit=crop', publicId: 'bureau-3', alt: 'Bureau industriel' }], dimensions: { length: 150, width: 70, height: 75, weight: 55 }, materials: ['Bois', 'Métal'], colors: ['Bois', 'Noir'], sku: 'BUREAU-INDUS-001', featured: false, inStock: true, stockQuantity: 10, brand: 'IronWood', tags: ['industriel'], rating: { average: 4.5, count: 13 } },
      { name: 'Bureau Ergonomique Réglable', description: 'Hauteur réglable pour télétravail', price: 265000, originalPrice: 305000, discount: 13, category: categoryMap['bureaux'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1661775522763-451d7783b453?q=80&w=1171&auto=format&fit=crop', publicId: 'bureau-4', alt: 'Bureau ergonomique' }], dimensions: { length: 140, width: 70, height: 75, weight: 45 }, materials: ['MDF', 'Métal'], colors: ['Blanc', 'Noir'], sku: 'BUREAU-ERGO-001', featured: true, inStock: true, stockQuantity: 8, brand: 'ErgoDesk', tags: ['ergonomique'], rating: { average: 4.7, count: 21 } },
      { name: 'Bureau Open Space', description: 'Grand plateau pour coworking', price: 225000, originalPrice: 260000, discount: 13, category: categoryMap['bureaux'], images: [{ url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1169&auto=format&fit=crop', publicId: 'bureau-5', alt: 'Bureau open space' }], dimensions: { length: 200, width: 80, height: 75, weight: 60 }, materials: ['Bois', 'Métal'], colors: ['Chêne', 'Noir'], sku: 'BUREAU-OPEN-001', featured: false, inStock: true, stockQuantity: 6, brand: 'Office Pro', tags: ['open-space'], rating: { average: 4.4, count: 12 } },

      // Plus 15 produits complémentaires
      { name: 'Armoire 4 Portes Bois', description: 'Grande armoire spacieuse', price: 425000, originalPrice: 485000, discount: 12, category: categoryMap['chambres'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1674815329610-a8cc3a56f877?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'armoire-1', alt: 'Armoire 4 portes' }], dimensions: { length: 160, width: 60, height: 200, weight: 120 }, materials: ['Bois', 'Miroir'], colors: ['Chêne'], sku: 'ARMOIRE-001', featured: false, inStock: true, stockQuantity: 8, brand: 'WoodStyle', tags: ['armoire', 'rangement'], rating: { average: 4.4, count: 15 } },
      { name: 'Commode 5 Tiroirs', description: 'Commode avec miroir intégré', price: 185000, originalPrice: 210000, discount: 12, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1621262402468-a1c27d6ba468?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'commode-1', alt: 'Commode 5 tiroirs' }], dimensions: { length: 120, width: 45, height: 140, weight: 60 }, materials: ['Bois', 'Verre'], colors: ['Blanc', 'Noir'], sku: 'COMMODE-001', featured: false, inStock: true, stockQuantity: 14, brand: 'ClassicHome', tags: ['commode', 'chambre'], rating: { average: 4.3, count: 12 } },
      { name: 'Chevets Modernes (paire)', description: 'Paire de chevets design minimaliste', price: 125000, originalPrice: 145000, discount: 14, category: categoryMap['chambres'], images: [{ url: 'https://img5.su-cdn.com/cdn-cgi/image/width=600,height=600,format=webp/mall/file/2023/11/23/793f8b8a62aea101d5bbc3403621a55e.jpg', publicId: 'chevets-1', alt: 'Chevets modernes' }], dimensions: { length: 50, width: 40, height: 50, weight: 20 }, materials: ['MDF', 'Métal'], colors: ['Blanc', 'Gris'], sku: 'CHEVETS-001', featured: false, inStock: true, stockQuantity: 20, brand: 'MinimalDesign', tags: ['chevets', 'chambre'], rating: { average: 4.5, count: 8 } },
      { name: 'Table Basse Salon Verre & Métal', description: 'Table basse moderne en verre fumé', price: 165000, originalPrice: 190000, discount: 13, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1647967527216-adea2f078e07?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'table-salon-1', alt: 'Table basse verre' }], dimensions: { length: 110, width: 60, height: 40, weight: 28 }, materials: ['Verre', 'Métal'], colors: ['Noir', 'Transparent'], sku: 'TABLE-VERRE-001', featured: false, inStock: true, stockQuantity: 16, brand: 'GlassDesign', tags: ['table basse'], rating: { average: 4.5, count: 11 } },
      { name: 'Buffet Salon Gris', description: 'Buffet de rangement élégant', price: 345000, originalPrice: 395000, discount: 13, category: categoryMap['salons'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1670685060306-198b9734429c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'buffet-1', alt: 'Buffet gris' }], dimensions: { length: 160, width: 50, height: 100, weight: 80 }, materials: ['MDF', 'Métal'], colors: ['Gris'], sku: 'BUFFET-001', featured: false, inStock: true, stockQuantity: 6, brand: 'StorageHome', tags: ['buffet', 'rangement'], rating: { average: 4.4, count: 9 } },
      { name: 'Étagères Murales (set 3)', description: 'Set de 3 étagères modernes', price: 95000, originalPrice: 115000, discount: 17, category: categoryMap['bureaux'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1680127402006-3a21c93da392?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'etageres-1', alt: 'Étagères murales' }], dimensions: { length: 120, width: 30, height: 30, weight: 15 }, materials: ['Métal', 'Bois'], colors: ['Noir', 'Blanc'], sku: 'ETAGERES-001', featured: false, inStock: true, stockQuantity: 25, brand: 'WallStyle', tags: ['étagères', 'rangement'], rating: { average: 4.3, count: 13 } },
      { name: 'Tabourets de Bar (set 4)', description: 'Set de 4 tabourets avec dossier', price: 185000, originalPrice: 225000, discount: 18, category: categoryMap['cuisines'], images: [{ url: 'https://img5.su-cdn.com/cdn-cgi/image/width=600,height=600,format=webp/mall/file/2023/05/11/03867834f18ab73a51a2594c1d83ff90.jpg', publicId: 'tabourets-1', alt: 'Tabourets bar' }], dimensions: { length: 45, width: 45, height: 100, weight: 35 }, materials: ['Tissu', 'Métal'], colors: ['Gris', 'Noir'], sku: 'TABOURETS-001', featured: true, inStock: true, stockQuantity: 11, brand: 'BarStyle', tags: ['tabourets', 'bar'], rating: { average: 4.6, count: 18 } },
      { name: 'Chaise de Cuisine Moderne', description: 'Chaise design pour cuisine', price: 75000, originalPrice: 89000, discount: 16, category: categoryMap['cuisines'], images: [{ url: 'https://images.unsplash.com/photo-1611464908623-07f19927264e?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'chaise-cuisine-1', alt: 'Chaise cuisine' }], dimensions: { length: 50, width: 55, height: 85, weight: 8 }, materials: ['Tissu', 'Métal'], colors: ['Bleu', 'Gris', 'Blanc'], sku: 'CHAISE-CUISINE-001', featured: false, inStock: true, stockQuantity: 30, brand: 'KitchenChair', tags: ['chaise'], rating: { average: 4.2, count: 7 } },
      { name: 'Îlot Central Cuisine', description: 'Îlot multifonctionnel pour cuisine', price: 485000, originalPrice: 545000, discount: 11, category: categoryMap['cuisines'], images: [{ url: 'https://media.istockphoto.com/id/1404283694/photo/interior-of-modern-kitchen-with-wooden-floor-and-large-table-in-center-of-room.jpg?s=2048x2048&w=is&k=20&c=Z1jVgVwgkGSvEDhzvLvaGybdt7w-bbXH49ULWOJcevw=', publicId: 'ilot-1', alt: 'Îlot central' }], dimensions: { length: 150, width: 80, height: 90, weight: 120 }, materials: ['Bois', 'Granite', 'Inox'], colors: ['Bois', 'Noir'], sku: 'ILOT-001', featured: false, inStock: true, stockQuantity: 3, brand: 'Kitchen Pro', tags: ['îlot', 'cuisine'], rating: { average: 4.7, count: 14 } },
      { name: 'Caisson Rangement Bureau', description: 'Caisson à 3 tiroirs pour bureau', price: 95000, originalPrice: 115000, discount: 17, category: categoryMap['bureaux'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1683573435604-1e1a81aa90d9?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'caisson-1', alt: 'Caisson rangement' }], dimensions: { length: 45, width: 45, height: 65, weight: 25 }, materials: ['MDF', 'Métal'], colors: ['Gris', 'Blanc'], sku: 'CAISSON-001', featured: false, inStock: true, stockQuantity: 18, brand: 'OfficePro', tags: ['rangement', 'bureau'], rating: { average: 4.4, count: 10 } },
      { name: 'Armoire Penderie Studio', description: 'Petite armoire pour studio', price: 155000, originalPrice: 185000, discount: 16, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1647481045013-8efc5594369d?q=80&w=728&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'armoire-studio-1', alt: 'Armoire studio' }], dimensions: { length: 100, width: 50, height: 180, weight: 70 }, materials: ['MDF'], colors: ['Blanc', 'Noir'], sku: 'ARMOIRE-STUDIO-001', featured: false, inStock: true, stockQuantity: 12, brand: 'CompactStyle', tags: ['armoire', 'studio'], rating: { average: 4.3, count: 6 } },
      { name: 'Miroir Mural Chambre', description: 'Grand miroir mural design', price: 125000, originalPrice: 155000, discount: 19, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1617228206053-477863025d9c?q=80&w=1152&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'miroir-1', alt: 'Miroir mural' }], dimensions: { length: 100, width: 5, height: 150, weight: 12 }, materials: ['Verre', 'Cadre métal'], colors: ['Noir', 'Or', 'Argent'], sku: 'MIROIR-001', featured: false, inStock: true, stockQuantity: 20, brand: 'MirrorStyle', tags: ['miroir', 'décoration'], rating: { average: 4.5, count: 9 } },
      { name: 'Petit Canapé Gris 2 Places', description: 'Canapé compact 2 places', price: 165000, originalPrice: 195000, discount: 15, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1560184897-67f4a3f9a7fa?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'petit-canape-1', alt: 'Petit canapé' }], dimensions: { length: 160, width: 85, height: 85, weight: 65 }, materials: ['Tissu', 'Bois'], colors: ['Gris'], sku: 'PETIT-CANAPE-001', featured: false, inStock: true, stockQuantity: 13, brand: 'SmallLiving', tags: ['canapé', 'compact'], rating: { average: 4.4, count: 8 } },
      { name: 'Méridienne Lounge', description: 'Méridienne pour salon', price: 235000, originalPrice: 275000, discount: 15, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1700786032675-2e96774127c4?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'meridienne-1', alt: 'Méridienne' }], dimensions: { length: 180, width: 70, height: 80, weight: 45 }, materials: ['Tissu', 'Bois'], colors: ['Bleu', 'Gris', 'Beige'], sku: 'MERIDIENNE-001', featured: false, inStock: true, stockQuantity: 9, brand: 'LoungeStyle', tags: ['méridienne', 'détente'], rating: { average: 4.5, count: 11 } },
      { name: 'Banc de Rangement Entrée', description: 'Banc avec tiroir de rangement', price: 165000, originalPrice: 195000, discount: 15, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1722859031320-00012b00e8ba?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'banc-1', alt: 'Banc rangement' }], dimensions: { length: 120, width: 50, height: 80, weight: 40 }, materials: ['Bois', 'Métal'], colors: ['Blanc', 'Chêne'], sku: 'BANC-001', featured: false, inStock: true, stockQuantity: 15, brand: 'EntryStyle', tags: ['banc', 'rangement'], rating: { average: 4.3, count: 7 } },
      { name: 'Plateau de Service Bois', description: 'Plateau de service design', price: 45000, originalPrice: 55000, discount: 18, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1559849327-ae1157eb88b2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'plateau-1', alt: 'Plateau service' }], dimensions: { length: 50, width: 35, height: 8, weight: 2 }, materials: ['Bois massif'], colors: ['Naturel', 'Teinté'], sku: 'PLATEAU-001', featured: false, inStock: true, stockQuantity: 40, brand: 'WoodAccent', tags: ['plateau', 'décoration'], rating: { average: 4.6, count: 5 } },
      { name: 'Repose-Pieds Salon Ottoman', description: 'Ottoman confortable', price: 95000, originalPrice: 120000, discount: 21, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1626551039948-ddd7e595fe06?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'ottoman-1', alt: 'Ottoman' }], dimensions: { length: 60, width: 60, height: 45, weight: 18 }, materials: ['Tissu', 'Mousse'], colors: ['Gris', 'Bleu'], sku: 'OTTOMAN-001', featured: false, inStock: true, stockQuantity: 17, brand: 'ComfortPods', tags: ['ottoman', 'repose-pieds'], rating: { average: 4.4, count: 6 } },
      { name: 'Tête de Lit Design', description: 'Tête de lit murale design moderne', price: 185000, originalPrice: 225000, discount: 18, category: categoryMap['chambres'], images: [{ url: 'https://images.unsplash.com/photo-1635286785966-512198a553ca?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'tete-lit-1', alt: 'Tête de lit' }], dimensions: { length: 200, width: 15, height: 120, weight: 50 }, materials: ['Tissu', 'Bois'], colors: ['Beige', 'Gris', 'Blanc'], sku: 'TETE-LIT-001', featured: false, inStock: true, stockQuantity: 11, brand: 'HeadBoard Pro', tags: ['tête de lit'], rating: { average: 4.4, count: 8 } },
      { name: 'Lampadaire Salon Led', description: 'Lampadaire moderne LED dimmable', price: 85000, originalPrice: 105000, discount: 19, category: categoryMap['salons'], images: [{ url: 'https://images.unsplash.com/photo-1673939859210-23d8444237ff?q=80&w=700&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'lampadaire-1', alt: 'Lampadaire' }], dimensions: { length: 30, width: 30, height: 160, weight: 8 }, materials: ['Métal', 'Textile'], colors: ['Noir', 'Blanc'], sku: 'LAMPADAIRE-001', featured: false, inStock: true, stockQuantity: 22, brand: 'LightStyle', tags: ['lampadaire', 'décoration'], rating: { average: 4.3, count: 6 } },
      { name: 'Porte Manteau Mural', description: 'Porte manteau design mural', price: 55000, originalPrice: 75000, discount: 27, category: categoryMap['chambres'], images: [{ url: 'https://plus.unsplash.com/premium_photo-1670968418657-805607e97742?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', publicId: 'portemanteau-1', alt: 'Porte manteau' }], dimensions: { length: 80, width: 10, height: 30, weight: 3 }, materials: ['Bois', 'Métal'], colors: ['Noir', 'Chêne'], sku: 'PORTEMANTEAU-001', featured: false, inStock: true, stockQuantity: 28, brand: 'WallHooks', tags: ['rangement', 'déco'], rating: { average: 4.2, count: 5 } }
    ];

    await Product.insertMany(products);

    // Activer tous les produits
    await Product.updateMany({}, { isActive: true });
    // Créer les paramètres admin par défaut
    const adminSettings = new AdminSettings({});
    await adminSettings.save();

    console.log('\n✅ Database seeded successfully!');
    console.log('📊 Summary:');
    console.log(`   - 👤 1 admin user created`);
    console.log(`   - 🏷️ ${categories.length} categories created`);
    console.log(`   - 🛋️ ${products.length} products created`);
    console.log(`   - ⚙️ Admin settings initialized`);
    console.log('\n🔑 Login credentials:');
    console.log(`   Email: admin@furniture-store.com`);
    console.log(`   Password: admin123`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedData();